const graphTypes = {
  FETCH_GRAPH_DATA: 'FETCH_GRAPH_DATA',
  SET_GRAPH_CATEGORY: 'SET_GRAPH_TYPE',
  SET_GRAPH_SCROLL_POSITION: 'SET_GRAPH_SCROLL_POSITION',
  //SCROLL_TO_DAY: 'SCROLL_TO_DAY',
  COLLAPSE_WEATHER_GRAPH: 'COLLAPSE_TEMP_GRAPH',
  EXPAND_WEATHER_GRAPH: 'EXPAND_WEATHER_GRAPH',
} as const

const forecastTypes = {
  FETCH_EXTENDED_FORECAST: 'FETCH_EXTENDED_FORECAST',
  FETCH_CURRENT_FORECAST: 'FETCH_CURRENT_FORECAST',
} as const

const settingsTypes = {
  FETCH_SETTINGS: 'FETCH_SETTINGS',
  SET_LOCATION: 'SET_LOCATION',
  SET_TIME_FORMAT: 'SET_TIME_FORMAT',
  SET_TEMP_UNITS: 'SET_TEMP_UNITS',
  SET_BACKGROUND: 'SET_DYNAMIC_BACKGROUND',
} as const

export const actionTypes = {
  ...graphTypes,
  ...settingsTypes,
  ...forecastTypes,
} as const
